
// int IDs for Qt Custom Events

#define SCREEN_MODE_CHANGE_EVENT 1
#define RELOAD_WALLPAPERS_EVENT 2
#define ADD_FILE_FROM_COMPUTER_EVENT 3
#define ADD_FILE_FROM_CACHE_EVENT 4
#define REMOVE_CACHE_EVENT 5
#define EDIT_CACHE_EVENT 6
#define CACHE_INFO_EVENT 7